export const FETCH_OVERVIEW_REVIEWS = 'FETCH_OVERVIEW_REVIEWS';
export const GET_RANKED_FEATURES = 'GET_RANKED_FEATURES';
export const OPEN_SIDEBAR_AND_FETCH_FULL_REVIEWS = 'OPEN_SIDEBAR_AND_FETCH_FULL_REVIEWS';
