export const FETCH_OVERVIEW_REVIEWS = 'FETCH_OVERVIEW_REVIEWS';
export const GET_RANKED_FEATURES = 'GET_RANKED_FEATURES';
export const OPEN_SIDEBAR_AND_FETCH_FULL_REVIEWS = 'OPEN_SIDEBAR_AND_FETCH_FULL_REVIEWS';
export const FETCH_REVIEWS_ON_PAGE = 'FETCH_REVIEWS_ON_PAGE';
export const TOGGLE_ENGLISH_ONLY_REVIEW_OPTION = 'TOGGLE_ENGLISH_ONLY_REVIEW_OPTION';
export const CHANGE_SORTBY = 'CHANGE_SORTBY';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
